modLoader = "javafml" #mandatory
loaderVersion = "[32,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GPL-3.0 License"
issueTrackerURL = "https://github.com/alRex-U/Throwability/issues/" #optional
[[mods]] #mandatory
modId = "throwability" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Throwability" #mandatory
updateJSONURL = "http://myurl.me/" #optional
displayURL = "http://example.com/" #optional
credits = "Thanks for this example mod goes to Java" #optional
authors = "alRex-U" #optional
description = '''
    This enable us throw everything
'''
[[dependencies.examplemod]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[32,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.examplemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.1,1.16.5)"
ordering = "NONE"
side = "BOTH"
